services:
  mysql:
    image: mysql:8.0
    container_name: trixi-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trixi_db
      MYSQL_USER: trixi_user
      MYSQL_PASSWORD: trixi_password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: trixi-app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=mysql

volumes:
  mysql_data:
